### ISSUE TITLE
Update packaging for components

### ISSUE THREAD

**Issue by ofhouse** [dealmore/terraform-aws-next-js#43]
We currently rely on an internal tool called `@dealmore/funny` for building the components (proxy, static-deployment) that are deployed as lambdas.
Since we currently only use the packaging part of the tool, we should replace it with [`ncc-zip`](https://github.com/ofhouse/ncc-zip).

# ToDo
- [x] Replace all occurrences of `@dealmore/funny` with `ncc-zip`
- [x] Republish all affected components
- [ ] Release new Terraform module version with the updated components
